import React from "react";

const LoadingDots = () => {
  return (
    <div>
      <svg
        xmlns='http://www.w3.org/2000/svg'
        xmlnsXlink='http://www.w3.org/1999/xlink'
        style={{
          margin: "auto",
          background: "tansparent",
          display: "block",
          shapeRendering: "auto",
        }}
        width='100px'
        height='70px'
        viewBox='0 0 100 100'
        preserveAspectRatio='xMidYMid'
      >
        <circle cx='84' cy='50' r='10' fill='#053c54'>
          <animate
            attributeName='r'
            repeatCount='indefinite'
            dur='0.5s'
            calcMode='spline'
            keyTimes='0;1'
            values='10;0'
            keySplines='0 0.5 0.5 1'
            begin='0s'
          ></animate>
          <animate
            attributeName='fill'
            repeatCount='indefinite'
            dur='2s'
            calcMode='discrete'
            keyTimes='0;0.25;0.5;0.75;1'
            values='#053c54;#4f8aa4;#43768b;#235469;#053c54'
            begin='0s'
          ></animate>
        </circle>
        <circle cx='16' cy='50' r='10' fill='#053c54'>
          <animate
            attributeName='r'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='0;0;10;10;10'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='0s'
          ></animate>
          <animate
            attributeName='cx'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='16;16;16;50;84'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='0s'
          ></animate>
        </circle>
        <circle cx='50' cy='50' r='10' fill='#235469'>
          <animate
            attributeName='r'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='0;0;10;10;10'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-0.5s'
          ></animate>
          <animate
            attributeName='cx'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='16;16;16;50;84'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-0.5s'
          ></animate>
        </circle>
        <circle cx='84' cy='50' r='10' fill='#43768b'>
          <animate
            attributeName='r'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='0;0;10;10;10'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-1s'
          ></animate>
          <animate
            attributeName='cx'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='16;16;16;50;84'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-1s'
          ></animate>
        </circle>
        <circle cx='16' cy='50' r='10' fill='#4f8aa4'>
          <animate
            attributeName='r'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='0;0;10;10;10'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-1.5s'
          ></animate>
          <animate
            attributeName='cx'
            repeatCount='indefinite'
            dur='2s'
            calcMode='spline'
            keyTimes='0;0.25;0.5;0.75;1'
            values='16;16;16;50;84'
            keySplines='0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1'
            begin='-1.5s'
          ></animate>
        </circle>
        {/* <!-- [ldio] generated by https://loading.io/ --> */}
      </svg>
    </div>
  );
};

export default LoadingDots;
